export const MOCKLOGIN = 'GLOBAL/MOCKLOGIN';
export const SHOWMESSAGE = 'GLOBAL/SHOWMESSAGE';

export const VERIFYCODE = 'GLOBAL/VERIFYCODE';
export const SIGNUP = 'GLOBAL/SIGNUP';
export const SIGNIN = 'GLOBAL/SIGNIN';
